[2025-04-13 21:45:52,609] INFO _log() L225   * Restarting with stat - call_trace=\\192.168.10.100\clientes\TAINA\.Taina\MVP\MVP2\env\Lib\site-packages\werkzeug\_internal.py L225 
[2025-04-13 22:21:56,701] INFO _log() L225   * Restarting with stat - call_trace=\\192.168.10.100\clientes\TAINA\.Taina\MVP\MVP2\env\Lib\site-packages\werkzeug\_internal.py L225 
[2025-04-14 15:27:12,449] INFO _log() L225   * Restarting with stat - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\env\Lib\site-packages\werkzeug\_internal.py L225 
[2025-04-14 15:28:37,476] ERROR get_exchange_rate() L165  Erro ao obter a taxa de câmbio: 429 Client Error: Too Many Requests for url: https://query1.finance.yahoo.com/v7/finance/quote?symbols=USDBRL=X - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\meu_app_API\app.py L165 
[2025-04-14 22:38:41,070] ERROR get_exchange_rate() L165  Erro ao obter a taxa de câmbio: 429 Client Error: Too Many Requests for url: https://query1.finance.yahoo.com/v7/finance/quote?symbols=USDBRL=X - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\meu_app_API\app.py L165 
[2025-04-14 22:38:46,285] ERROR get_exchange_rate() L165  Erro ao obter a taxa de câmbio: 429 Client Error: Too Many Requests for url: https://query1.finance.yahoo.com/v7/finance/quote?symbols=USDBRL=X - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\meu_app_API\app.py L165 
[2025-04-15 13:26:59,868] ERROR get_exchange_rate() L165  Erro ao obter a taxa de câmbio: 429 Client Error: Too Many Requests for url: https://query1.finance.yahoo.com/v7/finance/quote?symbols=USDBRL=X - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\meu_app_API\app.py L165 
[2025-04-15 13:43:54,412] INFO _log() L225   * Restarting with stat - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\env\Lib\site-packages\werkzeug\_internal.py L225 
[2025-04-15 13:44:24,131] INFO _log() L225   * Restarting with stat - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\env\Lib\site-packages\werkzeug\_internal.py L225 
[2025-04-15 13:44:27,815] INFO _log() L225   * Restarting with stat - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\env\Lib\site-packages\werkzeug\_internal.py L225 
[2025-04-15 13:44:31,578] INFO _log() L225   * Restarting with stat - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\env\Lib\site-packages\werkzeug\_internal.py L225 
[2025-04-15 13:44:36,196] INFO _log() L225   * Restarting with stat - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\env\Lib\site-packages\werkzeug\_internal.py L225 
[2025-04-15 13:44:39,352] INFO _log() L225   * Restarting with stat - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\env\Lib\site-packages\werkzeug\_internal.py L225 
[2025-04-15 13:45:11,303] INFO _log() L225   * Restarting with stat - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\env\Lib\site-packages\werkzeug\_internal.py L225 
[2025-04-15 13:45:47,302] ERROR get_exchange_rate() L165  Erro ao obter a taxa de câmbio: 'quoteResponse' - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\meu_app_API\app.py L165 
[2025-04-15 13:59:29,090] INFO _log() L225   * Restarting with stat - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\env\Lib\site-packages\werkzeug\_internal.py L225 
[2025-04-15 13:59:54,312] INFO _log() L225   * Restarting with stat - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\env\Lib\site-packages\werkzeug\_internal.py L225 
[2025-04-15 14:13:03,328] ERROR get_exchange_rate() L165  Erro ao obter a taxa de câmbio: ('Connection aborted.', ConnectionResetError(10054, 'Foi forçado o cancelamento de uma conexão existente pelo host remoto', None, 10054, None)) - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\meu_app_API\app.py L165 
[2025-04-15 14:36:08,469] WARNING del_funcionario() L145  Erro ao deletar funcionario #'Taina Costa', Funcionario não encontrado na base :/ - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\meu_app_API\app.py L145 
[2025-04-15 14:36:32,274] WARNING del_funcionario() L145  Erro ao deletar funcionario #'Taina Costa', Funcionario não encontrado na base :/ - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\meu_app_API\app.py L145 
[2025-04-15 14:37:20,730] WARNING del_funcionario() L145  Erro ao deletar funcionario #'Taina Costa', Funcionario não encontrado na base :/ - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\meu_app_API\app.py L145 
[2025-04-15 14:37:21,073] WARNING del_funcionario() L145  Erro ao deletar funcionario #'Taina Costa', Funcionario não encontrado na base :/ - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\meu_app_API\app.py L145 
[2025-04-15 14:37:21,267] WARNING del_funcionario() L145  Erro ao deletar funcionario #'Taina Costa', Funcionario não encontrado na base :/ - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\meu_app_API\app.py L145 
[2025-04-15 14:37:21,420] WARNING del_funcionario() L145  Erro ao deletar funcionario #'Taina Costa', Funcionario não encontrado na base :/ - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\meu_app_API\app.py L145 
[2025-04-15 14:37:21,591] WARNING del_funcionario() L145  Erro ao deletar funcionario #'Taina Costa', Funcionario não encontrado na base :/ - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\meu_app_API\app.py L145 
[2025-04-15 14:37:21,756] WARNING del_funcionario() L145  Erro ao deletar funcionario #'Taina Costa', Funcionario não encontrado na base :/ - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\meu_app_API\app.py L145 
[2025-04-15 14:37:21,930] WARNING del_funcionario() L145  Erro ao deletar funcionario #'Taina Costa', Funcionario não encontrado na base :/ - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\meu_app_API\app.py L145 
[2025-04-15 14:37:22,123] WARNING del_funcionario() L145  Erro ao deletar funcionario #'Taina Costa', Funcionario não encontrado na base :/ - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\meu_app_API\app.py L145 
[2025-04-15 14:37:22,297] WARNING del_funcionario() L145  Erro ao deletar funcionario #'Taina Costa', Funcionario não encontrado na base :/ - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\meu_app_API\app.py L145 
[2025-04-15 14:48:00,416] WARNING del_funcionario() L145  Erro ao deletar funcionario #'Karin', Funcionario não encontrado na base :/ - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\meu_app_API\app.py L145 
[2025-04-15 14:48:02,879] WARNING del_funcionario() L145  Erro ao deletar funcionario #'Karin', Funcionario não encontrado na base :/ - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\meu_app_API\app.py L145 
[2025-04-15 14:48:05,127] WARNING del_funcionario() L145  Erro ao deletar funcionario #'Taina Costa', Funcionario não encontrado na base :/ - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\meu_app_API\app.py L145 
[2025-04-15 14:49:07,757] WARNING del_funcionario() L145  Erro ao deletar funcionario #'Taina Costa', Funcionario não encontrado na base :/ - call_trace=C:\Users\Admin\Documents\GitHub\MVP2\meu_app_API\app.py L145 
